// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalamardoGameClient is the client API for CalamardoGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalamardoGameClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	JoinGame(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error)
	StartGame(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error)
	Juego1Msg(ctx context.Context, in *Juego1Request, opts ...grpc.CallOption) (*Juego1Reply, error)
}

type calamardoGameClient struct {
	cc grpc.ClientConnInterface
}

func NewCalamardoGameClient(cc grpc.ClientConnInterface) CalamardoGameClient {
	return &calamardoGameClient{cc}
}

func (c *calamardoGameClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/proto.CalamardoGame/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calamardoGameClient) JoinGame(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error) {
	out := new(JoinReply)
	err := c.cc.Invoke(ctx, "/proto.CalamardoGame/JoinGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calamardoGameClient) StartGame(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartReply, error) {
	out := new(StartReply)
	err := c.cc.Invoke(ctx, "/proto.CalamardoGame/StartGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calamardoGameClient) Juego1Msg(ctx context.Context, in *Juego1Request, opts ...grpc.CallOption) (*Juego1Reply, error) {
	out := new(Juego1Reply)
	err := c.cc.Invoke(ctx, "/proto.CalamardoGame/Juego1msg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalamardoGameServer is the server API for CalamardoGame service.
// All implementations must embed UnimplementedCalamardoGameServer
// for forward compatibility
type CalamardoGameServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	JoinGame(context.Context, *JoinRequest) (*JoinReply, error)
	StartGame(context.Context, *StartRequest) (*StartReply, error)
	Juego1Msg(context.Context, *Juego1Request) (*Juego1Reply, error)
	mustEmbedUnimplementedCalamardoGameServer()
}

// UnimplementedCalamardoGameServer must be embedded to have forward compatible implementations.
type UnimplementedCalamardoGameServer struct {
}

func (UnimplementedCalamardoGameServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedCalamardoGameServer) JoinGame(context.Context, *JoinRequest) (*JoinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGame not implemented")
}
func (UnimplementedCalamardoGameServer) StartGame(context.Context, *StartRequest) (*StartReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedCalamardoGameServer) Juego1Msg(context.Context, *Juego1Request) (*Juego1Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Juego1Msg not implemented")
}
func (UnimplementedCalamardoGameServer) mustEmbedUnimplementedCalamardoGameServer() {}

// UnsafeCalamardoGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalamardoGameServer will
// result in compilation errors.
type UnsafeCalamardoGameServer interface {
	mustEmbedUnimplementedCalamardoGameServer()
}

func RegisterCalamardoGameServer(s grpc.ServiceRegistrar, srv CalamardoGameServer) {
	s.RegisterService(&CalamardoGame_ServiceDesc, srv)
}

func _CalamardoGame_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalamardoGameServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CalamardoGame/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalamardoGameServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalamardoGame_JoinGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalamardoGameServer).JoinGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CalamardoGame/JoinGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalamardoGameServer).JoinGame(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalamardoGame_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalamardoGameServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CalamardoGame/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalamardoGameServer).StartGame(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalamardoGame_Juego1Msg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Juego1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalamardoGameServer).Juego1Msg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CalamardoGame/Juego1msg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalamardoGameServer).Juego1Msg(ctx, req.(*Juego1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CalamardoGame_ServiceDesc is the grpc.ServiceDesc for CalamardoGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalamardoGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CalamardoGame",
	HandlerType: (*CalamardoGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _CalamardoGame_SayHello_Handler,
		},
		{
			MethodName: "JoinGame",
			Handler:    _CalamardoGame_JoinGame_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _CalamardoGame_StartGame_Handler,
		},
		{
			MethodName: "Juego1msg",
			Handler:    _CalamardoGame_Juego1Msg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/Calamardo.proto",
}
